spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gb-heima/config-repo.git
          username: gb-heima
          password: 010223gbly,.
          basedir: /Users/Administrator/Desktop/springcloud_sell/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh